name: Update Active Tasks in README

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-active-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch open issues with 'active-task' label
        id: fetch_issues
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'active-task',
              state: 'open',
              per_page: 10
            });
            let list = '';
            if (issues.data.length === 0) {
              list = '\n_No active tasks at the moment!_\n';
            } else {
              for (const issue of issues.data) {
                list += `- [${issue.title}](${issue.html_url})\n`;
              }
            }
            core.setOutput('active_tasks', list);
            return list;

      - name: Update README.md
        uses: actions/github-script@v7
        env:
          ACTIVE_TASKS: ${{ steps.fetch_issues.outputs.active_tasks }}
        with:
          script: |
            const fs = require('fs');
            const readmePath = 'README.md';
            const start = '<!--START_ACTIVE_TASKS-->';
            const end = '<!--END_ACTIVE_TASKS-->';
            const readme = fs.readFileSync(readmePath, 'utf8');
            const activeTasks = process.env.ACTIVE_TASKS || '\n_No active tasks at the moment!_\n';
            const newSection = `${start}\n${activeTasks}${end}`;
            const newReadme = readme.replace(new RegExp(`${start}[\\s\\S]*${end}`), newSection);
            fs.writeFileSync(readmePath, newReadme);
          

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.TOK_TOK }}
        run: |
          git config user.name "Your Name"
          git config user.email "msayantan05@gmail.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git diff --cached --quiet || git commit -m 'Update active tasks in README [bot]'
          git push
          